### ISSUE TITLE
رابط تحميل التطبيق لا يعمل

### ISSUE THREAD

**Issue by Ammar64** [kady-x/login_page#1]
عند الضغط على رابط تحميل التطبيق يظهر لى خطأ 404.
أقترح أن ترفع نسخة apk فى الإطلاقات (releases)

**Comment by kady-x** [comment]
أهلاً! 😊

شكرًا على التنبيه بخصوص مشكلة خطأ 404 لما تضغط على رابط تحميل التطبيق. 🚫📥 أنا رفعت نسخة APK في الإصدارات (releases) زي ما قلت. دلوقتي ممكن تحمل التطبيق من هناك.

لو واجهتك أي مشكلة تانية أو عندك أي استفسار، لا تتردد تسألني. شكرًا لدعمك! 🙏✨
